### ISSUE TITLE
Question...

### ISSUE THREAD

**Issue by trimstray** [ShadowHatesYou/pipetap.sh#1]
Hi!

Can I add this one-liner:

```
ssh -A -C $1 tcpdump -s 0 -i $2 -w - $TCPDUMPFILTER | sudo wireshark -k -i -
```

to [this](https://github.com/trimstray/the-book-of-secret-knowledge#tool-tcpdump) helpers for tcpdump?

**Comment by ShadowHatesYou** [comment]
Feel free. The -A part isn't neccesarily required, but is left over from my use of a jumpbox. The "sudo" portion on wireshark isn't _required_, but my wireshark complains despite being granted Capabilities with setcap. 

A cleaner, clearer line for inclusion might be:

ssh -C user@host tcpdump -s 0 -i <interface> -w - $TCPDUMPFILTER | wireshark -k -i -
