### ISSUE TITLE
Never sudo when running Wireshark

### ISSUE THREAD

**Issue by JaapKeuter** [ShadowHatesYou/pipetap.sh#2]
https://github.com/ShadowHatesYou/pipetap.sh/blob/a7eb74e3322995a53c15cc527fc69ae99effd09f/pipetap.sh#L14

You should not run 4 million lines of (GUI) code as root. The chance of some compromise times the amount of damage it can do is just too great. Setup proper [permissions](https://superuser.com/questions/319865/how-to-set-up-wireshark-to-run-without-root-on-debian#489110) for [dumpcap](https://www.wireshark.org/docs/man-pages/dumpcap.html) (the capture engine) and you should be fine.

**Comment by ShadowHatesYou** [comment]
Yet wireshark still complains when granted capabilities w/ setcap, even though it's only capturing from STDIN.
